// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMkIDBIZQlUhk4v0Q0qsfpNJfkY5dUbMA',
    appId: '1:888615556949:web:8d80dd9e0737564a4001dc',
    messagingSenderId: '888615556949',
    projectId: 'convo-b4bc2',
    authDomain: 'convo-b4bc2.firebaseapp.com',
    storageBucket: 'convo-b4bc2.firebasestorage.app',
    measurementId: 'G-TB31VFH3WB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPw5gE_8vVD8-ybFi2b0flKET28KPc1_o',
    appId: '1:888615556949:android:71f4158bbd9a0cae4001dc',
    messagingSenderId: '888615556949',
    projectId: 'convo-b4bc2',
    storageBucket: 'convo-b4bc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChLGDeaSuLP0UbZHsWmcBH5f9jim5ANN0',
    appId: '1:888615556949:ios:4480d3396f292adf4001dc',
    messagingSenderId: '888615556949',
    projectId: 'convo-b4bc2',
    storageBucket: 'convo-b4bc2.firebasestorage.app',
    iosBundleId: 'com.example.convo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChLGDeaSuLP0UbZHsWmcBH5f9jim5ANN0',
    appId: '1:888615556949:ios:4480d3396f292adf4001dc',
    messagingSenderId: '888615556949',
    projectId: 'convo-b4bc2',
    storageBucket: 'convo-b4bc2.firebasestorage.app',
    iosBundleId: 'com.example.convo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMkIDBIZQlUhk4v0Q0qsfpNJfkY5dUbMA',
    appId: '1:888615556949:web:5686db50f6b580574001dc',
    messagingSenderId: '888615556949',
    projectId: 'convo-b4bc2',
    authDomain: 'convo-b4bc2.firebaseapp.com',
    storageBucket: 'convo-b4bc2.firebasestorage.app',
    measurementId: 'G-19BJBNDWZ1',
  );
}
